name: Build & Deploy Pages
on:
  push:
    branches: [ main ] # 改成你的主分支，很多项目是master

env:
  # 消除Node20过时警告
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v6

      - name: 配置 Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22 # 长期稳定版本，避开Node20/24兼容坑
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 构建项目
        run: npm run build

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # vite打包输出目录dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
